CREATE DATABASE CREDIT
GO
USE CREDIT
GO

CREATE TABLE LOG_PROPOSAL
(
    Id INT IDENTITY PRIMARY KEY,
    RequestedAmount DECIMAL NULL,
    Portion INT NULL,
    FirstPayment DATETIME NULL ,
    CreditType NVARCHAR(100)
)


CREATE TABLE TB_PROPOSAL
(
    Id INT IDENTITY PRIMARY KEY,
    RequestedAmount DECIMAL NOT NULL,
    Portion INT NOT NULL,
    FirstPayment DATETIME NOT NULL,
    CreditType NVARCHAR(100) NOT NULL
)

CREATE TABLE TB_CREDIT
(
     Id INT IDENTITY PRIMARY KEY,
     Amount DECIMAL NOT NULL,
     Interest DECIMAL NOT NULL,
     IdProposal INT NOT NULL,
     CONSTRAINT FK_PROPOSAL_CREDIT FOREIGN KEY (IdProposal)
     REFERENCES TB_PROPOSAL(Id)
     ON DELETE CASCADE
    ON UPDATE CASCADE
)

CREATE TABLE TB_NOTIFICATION
(
    Id INT IDENTITY PRIMARY KEY,
    Message NVARCHAR(700),
    IdCredit INT NOT NULL, 
    CONSTRAINT FK_CREDIT_NOTIFICATION FOREIGN KEY (IdCredit)
    REFERENCES TB_CREDIT(Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
